In [1]:
import numpy as np 
my_arr = np.arange(100000)
my_list = list(range(100000))



In [3]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 15.6 ms


In [9]:
%time for _ in range (10):my_list2 = [x * 2 for x in my_list]

Wall time: 84.6 ms


In [10]:
import numpy as np
data = np.random.randn(2, 4)

In [11]:
data

array([[-1.66818953, -1.74050196,  1.66528719, -0.12572559],
       [-1.26035893,  1.18789927,  1.35275732,  0.49480128]])

In [12]:
data * 20

array([[-33.36379066, -34.81003921,  33.30574375,  -2.51451179],
       [-25.20717864,  23.75798533,  27.05514644,   9.89602558]])

In [13]:
data + data

array([[-3.33637907, -3.48100392,  3.33057438, -0.25145118],
       [-2.52071786,  2.37579853,  2.70551464,  0.98960256]])

In [14]:
data + data 

array([[-3.33637907, -3.48100392,  3.33057438, -0.25145118],
       [-2.52071786,  2.37579853,  2.70551464,  0.98960256]])

In [15]:
data ++ data 

array([[-3.33637907, -3.48100392,  3.33057438, -0.25145118],
       [-2.52071786,  2.37579853,  2.70551464,  0.98960256]])

In [16]:
data.shape 
(2, 3)

(2, 3)

In [18]:
data.dtype

dtype('float64')

In [20]:
data1 = [1, 2, 4.5, 6, 7]
arr1 = np.array(data1)
arr1

array([1. , 2. , 4.5, 6. , 7. ])

In [21]:
data2 = [[1, 2, 3, 4, 5], [7, 8, 1, 9, 10]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  1,  9, 10]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 5)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
np.empty((2, 3, 3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [1.05695252e-307, 1.89146896e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 8.01097889e-307, 1.60220800e-306],
        [9.34609790e-307, 1.37962456e-306, 2.22522596e-306]]])

In [28]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.empty((2, 3, 2))

array([[[7.84424301e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.89146896e-307, 2.00325377e-076]],

       [[2.87973555e+180, 2.67901055e+184],
        [5.88461617e-062, 8.45337638e+169],
        [4.54798023e+174, 8.77516394e-071]]])

In [3]:
arr1 = np.array ([1, 2, 3], dtype = np.float64)
arr2 = np.array ([1, 2, 3], dtype = np.int32) 
arr1. dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

In [5]:
arr = np.array([3.7, 1.2, -2.6, 0.5, -12.9, 10.1])
arr

array([  3.7,   1.2,  -2.6,   0.5, -12.9,  10.1])

In [6]:
 arr.astype(np.int32) 

array([  3,   1,  -2,   0, -12,  10])

In [7]:
#array of strings representing numbers
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float) 


array([ 1.25, -9.6 , 42.  ])

In [8]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])