In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np


In [2]:
obj = pd.Series([4, 5, 6, -7, 8])
obj

0    4
1    5
2    6
3   -7
4    8
dtype: int64

In [3]:
obj.values

array([ 4,  5,  6, -7,  8], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [6]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2 ['a']

-5

In [9]:
obj2 [['c', 'd', 'b']]

c    3
d    4
b    7
dtype: int64

In [10]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [11]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
'b' in obj2 

True

In [13]:
'f' in obj2

False

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
states = ['california', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series (sdata, index = states)
obj4

california        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
pd.isnull(obj4)

california     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
obj3 + obj4

Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
california         NaN
dtype: float64

In [19]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
california        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [5]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year' : [2001, 2002, 2004, 2005, 2007, 2009],
 'population' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  population
0    Ohio  2001         1.5
1    Ohio  2002         1.7
2    Ohio  2004         3.6
3  Nevada  2005         2.4
4  Nevada  2007         2.9
5  Nevada  2009         3.2

In [23]:
frame.head()

state  year  population
0    Ohio  2001         1.5
1    Ohio  2002         1.7
2    Ohio  2004         3.6
3  Nevada  2005         2.4
4  Nevada  2007         2.9

In [25]:
pd.DataFrame(data, columns = ['year', 'state', 'population'])

year   state  population
0  2001    Ohio         1.5
1  2002    Ohio         1.7
2  2004    Ohio         3.6
3  2005  Nevada         2.4
4  2007  Nevada         2.9
5  2009  Nevada         3.2

In [29]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'population', 'debt'],
index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2


year   state  population debt
one    2001    Ohio         1.5  NaN
two    2002    Ohio         1.7  NaN
three  2004    Ohio         3.6  NaN
four   2005  Nevada         2.4  NaN
five   2007  Nevada         2.9  NaN
six    2009  Nevada         3.2  NaN

In [30]:
frame2.loc['three']

year          2004
state         Ohio
population     3.6
debt           NaN
Name: three, dtype: object

In [31]:
val = pd.Series ([-1.2, -2.1, -1.4,], index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  population  debt
one    2001    Ohio         1.5   NaN
two    2002    Ohio         1.7  -1.2
three  2004    Ohio         3.6   NaN
four   2005  Nevada         2.4  -2.1
five   2007  Nevada         2.9  -1.4
six    2009  Nevada         3.2   NaN

In [32]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  population  debt  eastern
one    2001    Ohio         1.5   NaN     True
two    2002    Ohio         1.7  -1.2     True
three  2004    Ohio         3.6   NaN     True
four   2005  Nevada         2.4  -2.1    False
five   2007  Nevada         2.9  -1.4    False
six    2009  Nevada         3.2   NaN    False

In [34]:

frame2.values

array([[2001, 'Ohio', 1.5, nan, True],
       [2002, 'Ohio', 1.7, -1.2, True],
       [2004, 'Ohio', 3.6, nan, True],
       [2005, 'Nevada', 2.4, -2.1, False],
       [2007, 'Nevada', 2.9, -1.4, False],
       [2009, 'Nevada', 3.2, nan, False]], dtype=object)

In [35]:
obj = pd.Series(range (3), index=['a', 'b', 'c'])
index = obj.index 
index

Index(['a', 'b', 'c'], dtype='object')

In [36]:
index[1:]

Index(['b', 'c'], dtype='object')

In [37]:
index[1]

'b'

In [40]:
labels = pd.Index(np.arange(3))
labels



Int64Index([0, 1, 2], dtype='int64')

In [41]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [44]:
 obj2.index is labels 

True

In [45]:
'ohio' in frame2


False

In [48]:
#Reindexing pandas is object is reindex
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [49]:
obj2 = obj.reindex (['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [53]:
obj3 = pd.Series (['blue', 'green', 'black'], index=[0, 1, 3])
obj3

0     blue
1    green
3    black
dtype: object

In [56]:
obj3.reindex(range(6), method='ffill')

0     blue
1    green
2    green
3    black
4    black
5    black
dtype: object

In [59]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
index =['a', 'd', 'b'],
columns=['Ohio', 'Texas', 'cCalifornia']) 
frame

Ohio  Texas  cCalifornia
a     0      1            2
d     3      4            5
b     6      7            8

In [61]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  cCalifornia
a   0.0    1.0          2.0
b   6.0    7.0          8.0
c   NaN    NaN          NaN
d   3.0    4.0          5.0

C:\Users\92341\Anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


california  Ohio  Oregon  Texas
a         NaN   0.0     NaN    1.0
b         NaN   6.0     NaN    7.0
c         NaN   NaN     NaN    NaN
d         NaN   3.0     NaN    4.0

In [64]:
#Dropping Entries
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [65]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
 data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [67]:
 data.drop(['two', 'four'], axis='columns') 

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [6]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [7]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [8]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [9]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [10]:
df1 = pd.DataFrame({'A': [1, 2]})


In [11]:
df2 = pd.DataFrame({'B': [3, 4]})


In [12]:
df1

A
0  1
1  2

In [13]:
df2

B
0  3
1  4

In [14]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))


In [15]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [16]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [17]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [18]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [20]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
#Sorting and Ranking

obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj


d    0
a    1
b    2
c    3
dtype: int64

In [26]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
index=['three', 'one'], 
columns=['d', 'a', 'b', 'c'])

frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [28]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [29]:
frame.sort_index(axis=1, ascending=False) 

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [30]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values() 

2   -3
3    2
0    4
1    7
dtype: int64

In [34]:
obj = pd.Series([7, -5, 2, 3, 2, 0, 4])
obj.rank()

0    7.0
1    1.0
2    3.5
3    5.0
4    3.5
5    2.0
6    6.0
dtype: float64

In [33]:
 obj.rank(method='first') 

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [35]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame


b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [36]:
frame.rank(axis='columns') 

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [37]:
#duplicate lables
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [38]:
obj['b']

b    2
b    3
dtype: int64

In [39]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df


0         1         2
a -0.861246  0.382400 -0.004539
a  2.754587  0.239751  0.209153
b  0.971478  1.290893 -1.408507
b -0.276067 -0.729215  0.416868

In [40]:
df.loc['b']

0         1         2
b  0.971478  1.290893 -1.408507
b -0.276067 -0.729215  0.416868

In [41]:
#Summarizing and Computing Descriptive Statistic

df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
[np.nan, np.nan], [0.75, -1.3]], 
index=['a', 'b', 'c', 'd'], 
columns=['one', 'two'])


In [42]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [43]:
 df.sum(axis='columns') 

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [46]:
df.mean(axis='columns', skipna=True) 

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [47]:
df.describe() 

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000